<?php

class RsvpsTableSeeder extends Seeder {

    public function run()
    {
    	// Uncomment the below to wipe the table clean before populating
    	DB::table('rsvps')->delete();

        $rsvps = array(
            ['name' => "Maria Ortega", 'guests' => 1],
            ['name' => "Richard Ortega", 'guests' => 1],
            ['name' => "Richard Matthew Ortega", 'guests' => 1],
            ['name' => "Nicole Rodriguez", 'guests' => 1],
            ['name' => "Gloria Del Valle", 'guests' => 0],
            ['name' => "Joseph Nardoci", 'guests' => 1],
            ['name' => "Sandra Nardoci", 'guests' => 1],
            ['name' => "EJ Bonilla", 'guests' => 1],
            ['name' => "Chaley Jackson", 'guests' => 1],
            ['name' => "Lourdes Ayala", 'guests' => 4],
            ['name' => "Ivan Ayala", 'guests' => 4],
            ['name' => "EJ's Grandma", 'guests' => 0],
            ['name' => "Mark Rivera", 'guests' => 1],
            ['name' => "Anthony Traverso", 'guests' => 0],
            ['name' => "Enrique Fuentes", 'guests' => 0],
            ['name' => "Ramel Page", 'guests' => 0],
            ['name' => "Steven Encarnacion", 'guests' => 1],
            ['name' => "Victor Espinosa", 'guests' => 1],
            ['name' => "Anthony Vitale", 'guests' => 1],
            ['name' => "Stu Yellin", 'guests' => 1],
            ['name' => "Catherine Vidal-Yellin", 'guests' => 1],
            ['name' => "Jonathan Perez", 'guests' => 0],
            ['name' => "Melissa Esquilin", 'guests' => 0],
            ['name' => "Chrystie Cruz", 'guests' => 1],
            ['name' => "Brandon Marlowe", 'guests' => 1],
            ['name' => "Blanca Diaz", 'guests' => 3],
            ['name' => "Sorlyz Pagan", 'guests' => 3],
            ['name' => "George Shulga", 'guests' => 3],
            ['name' => "Jose Casanova", 'guests' => 0],
            ['name' => "Vigermia Malave", 'guests' => 0],
            ['name' => "Stephanie Ryba", 'guests' => 1],
            ['name' => "Shannon Sutherland", 'guests' => 1],
            ['name' => "Craig Sutherland", 'guests' => 1],
            ['name' => "Erin Martin", 'guests' => 1],
            ['name' => "Elissa Reyes", 'guests' => 1],
            ['name' => "Alex Reyes", 'guests' => 1],
            ['name' => "Denise Forty", 'guests' => 0],
            ['name' => "Audeliz Choo Pollock", 'guests' => 1],
            ['name' => "Luis A. Diaz", 'guests' => 2],
            ['name' => "Margarita Diaz", 'guests' => 2],
            ['name' => "Janice Diaz", 'guests' => 2],
            ['name' => "Fred Del Valle", 'guests' => 1],
            ['name' => "Lillian Del Valle", 'guests' => 1],
            ['name' => "Ivette Del Valle", 'guests' => 1],
            ['name' => "Andrea Prieto", 'guests' => 3],
            ['name' => "Alejandro Prieto", 'guests' => 0],
            ['name' => "Cesar Prieto", 'guests' => 0],
            ['name' => "Alexandrea Prieto", 'guests' => 0],
            ['name' => "Mildred Torres", 'guests' => 0],
            ['name' => "Maria Yangas", 'guests' => 0],
            ['name' => "Lisa Vega", 'guests' => 0],
            ['name' => "Steve Torres", 'guests' => 0],
            ['name' => "Joey Pichardo", 'guests' => 0],
            ['name' => "Kenny Szal", 'guests' => 0],
            ['name' => "Stephanie Gonzalez", 'guests' => 0],
            ['name' => "Ivy Ye", 'guests' => 0],
            ['name' => "Jimmy Cepeda", 'guests' => 0],
            ['name' => "David Ye", 'guests' => 1],
            ['name' => "Aytza Pacheco", 'guests' => 1],
            ['name' => "Omar Lozada", 'guests' => 1],
            ['name' => "Alfonso Duran", 'guests' => 0],
            ['name' => "Tom Daly", 'guests' => 1],
            ['name' => "Eric Sander", 'guests' => 1],
            ['name' => "Danielle Gac Sander", 'guests' => 1],
            ['name' => "Olajide Aaromi", 'guests' => 1],
            ['name' => "Frank Roman", 'guests' => 3],
            ['name' => "Franky Roman", 'guests' => 0],
            ['name' => "Jasmine Roman", 'guests' => 0],
            ['name' => "Jordan Roman", 'guests' => 0],
            ['name' => "Peter Rojas", 'guests' => 1],
            ['name' => "Jose Beibe Diaz", 'guests' => 1],
            ['name' => "Javier Diaz", 'guests' => 0],
            ['name' => "Gabriel Diaz", 'guests' => 1],
            ['name' => "Antonio Alexis Feliciano", 'guests' => 2],
            ['name' => "Iris N. Diaz de Feliciano", 'guests' => 2],
            ['name' => "Antonio Alexis Feliciano", 'guests' => 2],
            ['name' => "Olivia Paglia", 'guests' => 1],
            ['name' => "Anthony Wright", 'guests' => 1],
            ['name' => "Jose A. Pagan", 'guests' => 1],
            ['name' => "Maria Acevedo", 'guests' => 0],
            ['name' => "Rosa Figueroa", 'guests' => 1],
            ['name' => "Natalia Chavez", 'guests' => 1],
            ['name' => "Hector Castano", 'guests' => 0],
            ['name' => "Michael Vega", 'guests' => 1],
            ['name' => "Carlos Rodriguez", 'guests' => 0],
        );

        // Uncomment the below to run the seeder
        DB::table('rsvps')->insert($rsvps);
    }

}